export const categoryIds = [
  "ai-coding",
  "research-evaluation",
  "design-prototyping",
  "data-infrastructure",
  "robotics-vision-3d",
  "deployment-operations",
  "norwegian-data",
  "astar-built",
] as const;

export type CategoryId = (typeof categoryIds)[number];
export type AstarStatus = "Used" | "Tested" | "Watching" | "Unverified";
export type AvailabilityState =
  | "yes"
  | "partial"
  | "mixed"
  | "source-available"
  | "no"
  | "not-applicable"
  | "unknown";

export type Category = {
  id: CategoryId;
  name: string;
  description: string;
};

export type Tool = {
  id: string;
  name: string;
  url: string;
  sourceUrl?: string;
  category: CategoryId;
  description: string;
  why: string;
  tags: readonly string[];
  openSource: {
    state: AvailabilityState;
    label: string;
  };
  selfHosting: {
    state: AvailabilityState;
    label: string;
  };
  astarStatus: AstarStatus;
  statusNote?: string;
  lastReviewed: `${number}-${number}-${number}`;
};

export const categories: readonly Category[] = [
  {
    id: "ai-coding",
    name: "AI coding",
    description: "Agents and assistants that work directly with code, repositories and developer workflows.",
  },
  {
    id: "research-evaluation",
    name: "Research and evaluation",
    description: "Tools for tracing, testing and measuring whether an AI system behaves as intended.",
  },
  {
    id: "design-prototyping",
    name: "Design and prototyping",
    description: "Fast, inspectable ways to shape interfaces, diagrams and human-in-the-loop workflows.",
  },
  {
    id: "data-infrastructure",
    name: "Data and infrastructure",
    description: "Practical building blocks for storage, retrieval, analytics and data interchange.",
  },
  {
    id: "robotics-vision-3d",
    name: "Robotics, computer vision and 3D",
    description: "Foundational software for perception, spatial data and machines that act in the world.",
  },
  {
    id: "deployment-operations",
    name: "Deployment and operations",
    description: "The unglamorous layer that makes useful systems repeatable, observable and operable.",
  },
  {
    id: "norwegian-data",
    name: "Norwegian data and public services",
    description: "Authoritative Norwegian sources that can ground systems in public, local facts.",
  },
  {
    id: "astar-built",
    name: "Astar-built tools",
    description: "Open-source systems made by Astar and published for others to inspect, use and improve.",
  },
];

export const tools = [
  {
    id: "codex",
    name: "OpenAI Codex",
    url: "https://github.com/openai/codex",
    sourceUrl: "https://github.com/openai/codex",
    category: "ai-coding",
    description: "A lightweight coding agent that runs from the terminal and works inside a repository.",
    why: "A strong reference for agentic, task-oriented software work with an inspectable local client.",
    tags: ["agent", "CLI", "software engineering"],
    openSource: { state: "yes", label: "Yes · Apache-2.0" },
    selfHosting: { state: "partial", label: "Partial · local client, model service required" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "aider",
    name: "Aider",
    url: "https://aider.chat/",
    sourceUrl: "https://github.com/Aider-AI/aider",
    category: "ai-coding",
    description: "Terminal-based pair programming with repository maps, model choice and git-aware edits.",
    why: "It keeps the coding loop close to source control and makes model-provider trade-offs visible.",
    tags: ["pair programming", "CLI", "git"],
    openSource: { state: "yes", label: "Yes · Apache-2.0" },
    selfHosting: { state: "partial", label: "Partial · local client, model endpoint required" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "continue",
    name: "Continue",
    url: "https://continue.dev/",
    sourceUrl: "https://github.com/continuedev/continue",
    category: "ai-coding",
    description: "An open-source coding agent with IDE integrations and configurable model backends.",
    why: "Useful when teams need a provider-flexible assistant that can fit existing editor workflows.",
    tags: ["agent", "IDE", "provider-neutral"],
    openSource: { state: "yes", label: "Yes · Apache-2.0" },
    selfHosting: { state: "partial", label: "Partial · client and local models supported" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "openhands",
    name: "OpenHands",
    url: "https://openhands.dev/",
    sourceUrl: "https://github.com/OpenHands/OpenHands",
    category: "ai-coding",
    description: "A platform for running software-development agents in controlled workspaces.",
    why: "It is a useful reference for sandboxing, agent runtimes and repeatable software tasks.",
    tags: ["agent runtime", "sandbox", "automation"],
    openSource: { state: "yes", label: "Yes · MIT" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "langfuse",
    name: "Langfuse",
    url: "https://langfuse.com/",
    sourceUrl: "https://github.com/langfuse/langfuse",
    category: "research-evaluation",
    description: "Tracing, evaluation, prompt management and datasets for applications built with language models.",
    why: "It brings operational evidence and evaluation into one workflow without forcing a single model provider.",
    tags: ["observability", "evaluation", "tracing"],
    openSource: { state: "mixed", label: "Open core · MIT plus enterprise terms" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "phoenix",
    name: "Arize Phoenix",
    url: "https://arize.com/docs/phoenix",
    sourceUrl: "https://github.com/Arize-ai/phoenix",
    category: "research-evaluation",
    description: "AI observability and evaluation tooling for traces, experiments and retrieval systems.",
    why: "A practical investigation surface when quality failures span prompts, retrieval and model calls.",
    tags: ["observability", "RAG", "experiments"],
    openSource: { state: "source-available", label: "Source-available · ELv2" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "deepeval",
    name: "DeepEval",
    url: "https://deepeval.com/",
    sourceUrl: "https://github.com/confident-ai/deepeval",
    category: "research-evaluation",
    description: "A test framework for language-model applications with metrics for agents and RAG pipelines.",
    why: "It makes evaluation executable in familiar test and CI workflows instead of leaving it in notebooks.",
    tags: ["testing", "RAG", "CI"],
    openSource: { state: "yes", label: "Yes · Apache-2.0" },
    selfHosting: { state: "partial", label: "Partial · framework is local; models may be remote" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "promptfoo",
    name: "promptfoo",
    url: "https://promptfoo.dev/",
    sourceUrl: "https://github.com/promptfoo/promptfoo",
    category: "research-evaluation",
    description: "Declarative testing, comparison and red teaming for prompts, agents and retrieval systems.",
    why: "It supports reproducible checks across providers and works well as a release gate in CI.",
    tags: ["red teaming", "testing", "provider-neutral"],
    openSource: { state: "yes", label: "Yes · MIT" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "ragas",
    name: "Ragas",
    url: "https://docs.ragas.io/",
    sourceUrl: "https://github.com/vibrantlabsai/ragas",
    category: "research-evaluation",
    description: "An evaluation framework focused on language-model applications, especially retrieval-augmented systems.",
    why: "It provides a concrete starting point for measuring retrieval and response quality separately.",
    tags: ["RAG", "metrics", "experiments"],
    openSource: { state: "yes", label: "Yes · Apache-2.0" },
    selfHosting: { state: "partial", label: "Partial · framework is local; models may be remote" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "penpot",
    name: "Penpot",
    url: "https://penpot.app/",
    sourceUrl: "https://github.com/penpot/penpot",
    category: "design-prototyping",
    description: "A collaborative design and prototyping platform built around open web standards.",
    why: "It gives product and engineering teams an inspectable, self-hostable design workspace.",
    tags: ["interface design", "prototyping", "collaboration"],
    openSource: { state: "yes", label: "Yes · MPL-2.0" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "excalidraw",
    name: "Excalidraw",
    url: "https://excalidraw.com/",
    sourceUrl: "https://github.com/excalidraw/excalidraw",
    category: "design-prototyping",
    description: "A low-friction whiteboard for diagrams, system sketches and collaborative thinking.",
    why: "Fast diagrams are often the shortest path to aligning a team on an AI system boundary.",
    tags: ["diagramming", "whiteboard", "collaboration"],
    openSource: { state: "yes", label: "Yes · MIT" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "storybook",
    name: "Storybook",
    url: "https://storybook.js.org/",
    sourceUrl: "https://github.com/storybookjs/storybook",
    category: "design-prototyping",
    description: "A workshop for building, documenting and testing interface components in isolation.",
    why: "AI interfaces need explicit states for latency, uncertainty, partial results and failure—not only a happy path.",
    tags: ["components", "UI testing", "documentation"],
    openSource: { state: "yes", label: "Yes · MIT" },
    selfHosting: { state: "yes", label: "Yes · static output" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "xyflow",
    name: "React Flow",
    url: "https://reactflow.dev/",
    sourceUrl: "https://github.com/xyflow/xyflow",
    category: "design-prototyping",
    description: "Composable React components for node-based editors, workflows and visual graphs.",
    why: "Useful for making agent flows and human checkpoints visible when a plain form is not enough.",
    tags: ["React", "node editor", "workflow"],
    openSource: { state: "yes", label: "Yes · MIT" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    url: "https://www.postgresql.org/",
    sourceUrl: "https://git.postgresql.org/gitweb/?p=postgresql.git",
    category: "data-infrastructure",
    description: "A mature relational database with strong transactions, indexing and an extensive extension ecosystem.",
    why: "A dependable default for systems that need auditable state before they need exotic infrastructure.",
    tags: ["database", "SQL", "transactions"],
    openSource: { state: "yes", label: "Yes · PostgreSQL License" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "pgvector",
    name: "pgvector",
    url: "https://github.com/pgvector/pgvector",
    sourceUrl: "https://github.com/pgvector/pgvector",
    category: "data-infrastructure",
    description: "Vector similarity search as a PostgreSQL extension, with exact and approximate indexes.",
    why: "It can keep embeddings beside operational data and delay a separate vector database until it is justified.",
    tags: ["vector search", "PostgreSQL", "embeddings"],
    openSource: { state: "yes", label: "Yes · PostgreSQL License" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "qdrant",
    name: "Qdrant",
    url: "https://qdrant.tech/",
    sourceUrl: "https://github.com/qdrant/qdrant",
    category: "data-infrastructure",
    description: "A vector search engine with filtering, distributed deployment and a managed-cloud option.",
    why: "A focused option when vector retrieval has outgrown the operational shape of an extension.",
    tags: ["vector database", "retrieval", "Rust"],
    openSource: { state: "yes", label: "Yes · Apache-2.0" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "duckdb",
    name: "DuckDB",
    url: "https://duckdb.org/",
    sourceUrl: "https://github.com/duckdb/duckdb",
    category: "data-infrastructure",
    description: "An in-process analytical SQL database designed for fast local work on tabular data.",
    why: "It is a small, effective bridge between raw files, notebooks and reproducible data preparation.",
    tags: ["analytics", "SQL", "embedded"],
    openSource: { state: "yes", label: "Yes · MIT" },
    selfHosting: { state: "yes", label: "Yes · embedded" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "apache-arrow",
    name: "Apache Arrow",
    url: "https://arrow.apache.org/",
    sourceUrl: "https://github.com/apache/arrow",
    category: "data-infrastructure",
    description: "A language-independent columnar memory format and toolkit for efficient data interchange.",
    why: "It reduces needless serialization between the many runtimes that practical AI systems accumulate.",
    tags: ["columnar", "interchange", "analytics"],
    openSource: { state: "yes", label: "Yes · Apache-2.0" },
    selfHosting: { state: "not-applicable", label: "Not applicable · library and format" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "ros-2",
    name: "ROS 2",
    url: "https://docs.ros.org/en/rolling/",
    sourceUrl: "https://github.com/ros2",
    category: "robotics-vision-3d",
    description: "A modular set of libraries and tools for building distributed robot software.",
    why: "It supplies the communication, lifecycle and tooling layer needed beyond a one-off hardware demo.",
    tags: ["robotics", "middleware", "distributed systems"],
    openSource: { state: "mixed", label: "Yes · primarily Apache-2.0 and BSD" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "opencv",
    name: "OpenCV",
    url: "https://github.com/opencv/opencv",
    sourceUrl: "https://github.com/opencv/opencv",
    category: "robotics-vision-3d",
    description: "A broad computer-vision library spanning image processing, calibration, tracking and inference utilities.",
    why: "It remains a useful baseline for deterministic vision work around learned models.",
    tags: ["computer vision", "image processing", "C++"],
    openSource: { state: "yes", label: "Yes · Apache-2.0" },
    selfHosting: { state: "yes", label: "Yes · library" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "open3d",
    name: "Open3D",
    url: "https://www.open3d.org/",
    sourceUrl: "https://github.com/isl-org/Open3D",
    category: "robotics-vision-3d",
    description: "A library for 3D data processing, including point clouds, meshes, registration and reconstruction.",
    why: "It offers practical primitives for checking and processing spatial outputs before building custom geometry code.",
    tags: ["3D", "point clouds", "reconstruction"],
    openSource: { state: "yes", label: "Yes · MIT" },
    selfHosting: { state: "yes", label: "Yes · library" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "blender",
    name: "Blender",
    url: "https://www.blender.org/",
    sourceUrl: "https://github.com/blender/blender",
    category: "robotics-vision-3d",
    description: "A complete 3D creation suite with scripting, rendering, simulation and data-preparation workflows.",
    why: "Its Python API makes it valuable for synthetic scenes, inspection assets and reproducible visual pipelines.",
    tags: ["3D", "simulation", "synthetic data"],
    openSource: { state: "yes", label: "Yes · GPL" },
    selfHosting: { state: "yes", label: "Yes · desktop and headless" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "colmap",
    name: "COLMAP",
    url: "https://colmap.github.io/",
    sourceUrl: "https://github.com/colmap/colmap",
    category: "robotics-vision-3d",
    description: "A structure-from-motion and multi-view stereo pipeline with command-line and graphical interfaces.",
    why: "It is a strong classical baseline for testing whether captured views support real reconstruction.",
    tags: ["photogrammetry", "reconstruction", "multi-view"],
    openSource: { state: "yes", label: "Yes · BSD-3-Clause" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "moby",
    name: "Moby",
    url: "https://mobyproject.org/",
    sourceUrl: "https://github.com/moby/moby",
    category: "deployment-operations",
    description: "Open components for assembling container-based systems, including the engine behind Docker.",
    why: "Containers remain a practical unit for making model services and dependencies repeatable.",
    tags: ["containers", "runtime", "packaging"],
    openSource: { state: "yes", label: "Yes · Apache-2.0" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    url: "https://kubernetes.io/",
    sourceUrl: "https://github.com/kubernetes/kubernetes",
    category: "deployment-operations",
    description: "A platform for scheduling and operating containerised workloads across clusters.",
    why: "Relevant once service count, availability and deployment policy justify the added operational surface.",
    tags: ["orchestration", "containers", "infrastructure"],
    openSource: { state: "yes", label: "Yes · Apache-2.0" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "opentelemetry",
    name: "OpenTelemetry",
    url: "https://opentelemetry.io/",
    sourceUrl: "https://github.com/open-telemetry",
    category: "deployment-operations",
    description: "Vendor-neutral standards and tooling for collecting traces, metrics and logs.",
    why: "AI systems cross many service boundaries; portable telemetry prevents observability from becoming a lock-in choice.",
    tags: ["telemetry", "tracing", "standards"],
    openSource: { state: "yes", label: "Yes · Apache-2.0" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "grafana",
    name: "Grafana OSS",
    url: "https://grafana.com/oss/grafana/",
    sourceUrl: "https://github.com/grafana/grafana",
    category: "deployment-operations",
    description: "A composable interface for exploring and presenting metrics, logs and traces from many sources.",
    why: "It turns operational signals into a shared view for the people responsible for a system after launch.",
    tags: ["observability", "dashboards", "operations"],
    openSource: { state: "yes", label: "Yes · AGPL-3.0" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "nextjs",
    name: "Next.js",
    url: "https://nextjs.org/",
    sourceUrl: "https://github.com/vercel/next.js",
    category: "deployment-operations",
    description: "A React framework for server-rendered and statically generated web applications.",
    why: "It can ship a fast static surface while leaving room for carefully scoped server behaviour when needed.",
    tags: ["web", "React", "static generation"],
    openSource: { state: "yes", label: "Yes · MIT" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Used",
    statusNote: "Used for Astar’s current public web stack, including this directory.",
    lastReviewed: "2026-09-03",
  },
  {
    id: "vercel",
    name: "Vercel",
    url: "https://vercel.com/",
    sourceUrl: "https://github.com/vercel/vercel",
    category: "deployment-operations",
    description: "A managed deployment platform for web applications with branch previews and a global delivery network.",
    why: "Preview deployments make visual and product review a distinct gate before production promotion.",
    tags: ["hosting", "preview deployments", "web"],
    openSource: { state: "mixed", label: "Mixed · CLI Apache-2.0; platform proprietary" },
    selfHosting: { state: "no", label: "No · managed platform" },
    astarStatus: "Used",
    statusNote: "Used for Astar web previews and hosting.",
    lastReviewed: "2026-09-03",
  },
  {
    id: "data-norge",
    name: "Data.norge.no",
    url: "https://data.norge.no/en/technical/api",
    sourceUrl: "https://github.com/Informasjonsforvaltning",
    category: "norwegian-data",
    description: "Norway’s national catalogue for discovering datasets, APIs, concepts and public services.",
    why: "It is the first place to check whether an authoritative Norwegian source already exists.",
    tags: ["Norway", "open data", "catalogue"],
    openSource: { state: "yes", label: "Yes · portal services Apache-2.0" },
    selfHosting: { state: "partial", label: "Partial · source available; national catalogue is hosted" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "ssb-api",
    name: "Statistics Norway API",
    url: "https://www.ssb.no/en/api/pxwebapiv2",
    category: "norwegian-data",
    description: "Programmatic access to tables in Statistics Norway’s Statbank through the PxWeb API.",
    why: "Official statistics are a better grounding source than copied figures with lost definitions and dates.",
    tags: ["Norway", "statistics", "public API"],
    openSource: { state: "unknown", label: "Unknown · service implementation" },
    selfHosting: { state: "no", label: "No · hosted public API" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "brreg-api",
    name: "Brønnøysund Register API",
    url: "https://data.brreg.no/enhetsregisteret/api/dokumentasjon/no/index.html",
    category: "norwegian-data",
    description: "Open REST access to organisations and sub-entities in Norway’s Central Coordinating Register.",
    why: "It is an authoritative base for organisation identity, rather than fuzzy names copied between systems.",
    tags: ["Norway", "organisations", "public API"],
    openSource: { state: "unknown", label: "Unknown · service implementation" },
    selfHosting: { state: "no", label: "No · hosted public API" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "kartverket-api",
    name: "Kartverket APIs",
    url: "https://www.kartverket.no/en/api-and-data",
    sourceUrl: "https://github.com/kartverket",
    category: "norwegian-data",
    description: "Open maps, addresses, elevation models and geospatial services from the Norwegian Mapping Authority.",
    why: "Spatial systems should start with the authoritative coordinates, boundaries and addresses available for Norway.",
    tags: ["Norway", "geospatial", "maps"],
    openSource: { state: "mixed", label: "Mixed · some service code is public" },
    selfHosting: { state: "partial", label: "Partial · downloads available; APIs are hosted" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "entur-api",
    name: "Entur APIs",
    url: "https://developer.entur.org/",
    sourceUrl: "https://github.com/entur",
    category: "norwegian-data",
    description: "National public-transport data and journey-planning APIs for stops, routes and mobility services.",
    why: "A strong public building block for travel assistants and services that need Norwegian transport context.",
    tags: ["Norway", "transport", "GraphQL"],
    openSource: { state: "mixed", label: "Mixed · many components EUPL-1.2" },
    selfHosting: { state: "partial", label: "Partial · components public; national APIs are hosted" },
    astarStatus: "Watching",
    lastReviewed: "2026-09-03",
  },
  {
    id: "nm-ai-platform",
    name: "NM AI Platform",
    url: "https://github.com/astar-as/nm-ai-platform",
    sourceUrl: "https://github.com/astar-as/nm-ai-platform",
    category: "astar-built",
    description: "A task-agnostic platform for running AI competitions with reusable challenge infrastructure.",
    why: "It publishes the operational shell for fair, repeatable AI challenges instead of hiding it behind an event site.",
    tags: ["competitions", "evaluation", "Astar"],
    openSource: { state: "yes", label: "Yes · MIT" },
    selfHosting: { state: "yes", label: "Yes" },
    astarStatus: "Used",
    statusNote: "Built and maintained by Astar.",
    lastReviewed: "2026-09-03",
  },
] as const satisfies readonly Tool[];

export const statusDefinitions: Readonly<Record<AstarStatus, string>> = {
  Used: "Evidence exists that Astar uses the tool in ongoing work.",
  Tested: "Astar has completed a documented hands-on evaluation.",
  Watching: "In scope and followed; inclusion is not a usage or recommendation claim.",
  Unverified: "Astar’s assessment is incomplete; treat the entry as a lead, not a conclusion.",
};
